### PR TITLE
Adds Support for FTicker

### PR DESCRIPTION
**Pull request by osstony**
There is still an issue where the py_callable could be garbage collected but still be called by the FTicker. I will look more into this and get a fix out for that soon. I did a quick test with this and pumping the PyQt/PySide event loop and it appears to work.

### CODE REVIEW

**Comment by rdeioris** [comment]
Hi, do you think is it possible to use the already available UPythonDelegate class for the callback ?

**Comment by osstony** [comment]
Hey @rdeioris, it could definitely be possible. The only reason I did it this way was because of my previous tests. I just ported over the code I had already written. I will give using the UPythonDelegate a try and see if we can use that instead.

**Comment by osstony** [comment]
Hey @rdeioris I finally have time to dig back into this and replace the FTickerDelegate with a UPythonDelegate. Could you expand on how you see UPythonDelegate being used here? Are you thinking that a new method would be added to UPythonDelegate to be passed to the FTicker::AddTicker method? Something like:

    bool UPythonDelegate::PyTickerHandler(float delta) 
    {
        PyGILState_STATE gstate;
        gstate = PyGILState_Ensure();

        PyObject *ret = PyObject_CallFunction(py_callable, "f", delta);
        if (!ret) {
            unreal_engine_py_log_error();
            return false;
        }

        bool result = false;
        if (ret == Py_True) result = true;
        Py_DECREF(ret);
        PyGILState_Release(gstate);
        return result;
    }

And then in the UEPyModule add_ticker function have:

    PyObject *py_ue_add_ticker(PyObject * self, PyObject * args) {

        float delay;
        PyObject *py_callable;
        if (!PyArg_ParseTuple(args, "Of:add_ticker", &py_callable, &delay)) {
            return NULL;
        }

        if (!PyCallable_Check(py_callable))
            return PyErr_Format(PyExc_Exception, "object is not a callable");

        UPythonDelegate *py_delegate = NewObject<UPythonDelegate>();
        py_delegate->SetPyCallable(py_callable);
        py_delegate->AddToRoot();
        
        FDelegateHandle ticker_delegate = FTicker::GetCoreTicker().AddTicker(FTickerDelegate::Create(py_delegate, UPythonDelegate::PyTickerHandler), delay);
        return (PyObject *)py_delegate;
    }

The above doesn't work yet, just psuedo code to get your opinion. Also, would we return the UPythonDelegate in python so a user could remove the ticker later if they desire?

**Comment by rdeioris** [comment]
hi, i am working on a new branch where we can play with threading, i will ping you as soon as it is ready

**Comment by rdeioris** [comment]
Hi again, if you pull the new code (again the master branch) you can un-comment the

```c
//#define UEPY_THREADING 1
```

directive in UnrealEnginePythonPrivatePCH.h

Once rebuilt, the plugin will get full threading support.

It is not on by default because:

* i need to make some benchmark about the impact of constantly acquiring and releasing the GIL (for example in uWSGI it is pretty high)
* i need a bigger test suite


btw as you can see from the code you only need to add 

```c
FScopePythonGIL gil;
```

before entering the python vm, the  RAII wil lautomatically release the gil at the end of the scope.

Regarding UPythonDelegate, check the UEPYTimer.cpp file for how i implemented it

**Comment by osstony** [comment]
@rdeioris thanks! I've rebased the python2.7_support branch against your latest changes and pushed it up. The other pull request has those changes.

**Comment by rdeioris** [comment]
unreal_engine.add_ticker(callable[,delay]) has been added. Thanks a lot for your contribution. Would you like to add your credits to the CONTRIBUTORS file i have added to the repository ?

**Pull request closed without merging**
