### PR TITLE
Add new functions to support creating and updating material instances

### PR DESCRIPTION
**Pull request by jiamingfeng**
Add new functions to support creating and updating material instances
Updated import assets function to be able to import assets in a batch
Updated add component to blueprint to be able to add to a parent

### CODE REVIEW

**Comment by rdeioris** [comment]
Looks really good, can you bring back support for passing a string (in addition to a list) to the asset import function (just ad a PyUnicode_Check()) ? There are people already using it and i would like to not break backward compatibilty.

Please add your credits to the CONTRIBUTORS file

**Comment by rdeioris** [comment]
@jiamingfeng hi, can you update the pull request with my suggestions ? thanks a lot

**Comment by jiamingfeng** [comment]
Sorry about that. I was a bit hammered by work recently. Will try to update the pull request today.
Cheers.

**Comment by jiamingfeng** [comment]
Updated the code to added back the default implementation of import_asset back

**Comment by rdeioris** [comment]
Manually merged, thanks a lot

**Pull request closed without merging**
